# -*- coding: utf-8 -*-
"""Week 8 Practice Notebook: Connecting to Neo4j - Breakout 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yz_ctCXZJuL3lsbvIjCQ-NwL8_Yhgs9d

# Practice Notebook: Connecting to Neo4j
"""

!pip install neo4j

from neo4j import GraphDatabase

#Set the connection details:
bolt_url = "neo4j+s://f680248d.databases.neo4j.io"
user = "neo4j"
password = "CV5io6VC99r107hqaJKPcwBukDFNJ1FTh3pHit4NoCM"

#Connect to the database:
driver = GraphDatabase.driver(bolt_url, auth=(user, password))

#Running a test query
with driver.session() as session:
    result = session.run("RETURN 1")
    for record in result:
        print(record)

# Close the driver instance
driver.close()

"""## Challenge

In this challenge, you will deploy a Neo4j database on Neo4j Aura and then connect to it using Python. The challenge has two parts:
* Deploy a Neo4j database on Neo4j Aura.
* Connect to the database using Python and run a simple query.
"""

# Your code goes here

"""### Sample solution"""

from neo4j import GraphDatabase
bolt_url = ""
user = "neo4j"
password = ""

driver = GraphDatabase.driver(bolt_url, auth=(user, password))

with driver.session() as session:
    result = session.run("RETURN 1")
    for record in result:
        print(record)
driver.close()

"""## Thursday: Writing Data to a Neo4J Database"""